### ISSUE TITLE
Bug collection

### ISSUE THREAD

**Issue by NeatWolf** [Dio93/LC-DuckMod#1]
Hi there!

I was about to submit a few bugs I think I've found but - apparently you've updated the project recently?

Is there going to be a new version in the thunderstore in the near future?

I surely hope so, that's an adorable addition to LC! I can see my other players wanting one of them for themselves ^^

Bugs apart, One major annoyance is that - all is fine if you're not using other mods. But, as soon as your base speed is not the vanilla one, the duck can't keep up with the player (think about LateGameUpdates speed boost), so it never drops the item when the player arrives on the ship, and is forever stuck in the middle of the map while players are zooming around.

Maybe implement some rubber-banding, so the duck speed is proportional to the distance to its owner? Not sure how easily that is going to sync with other players. Maybe just being slightly faster than the player (periodically checking if the player's speed changes) is simpler?

**Comment by Dio93** [comment]
Glad you like the mod. There will be updates on thunderstore, yes. But I haven't fixed any bugs yet. So feel free to submit whatever you find.

I can make the speed proportional to the players speed. But making the duck faster than players won't do a thing because the duck always follows the nearest player.

I will publish an update on thunderstore in the next few days. If the problem still appears, please let me know.

**Comment by NeatWolf** [comment]
I see - I thought I saw some fixes around so I was waiting for the next update before reporting anything.
Thanks for adding the rubberbanding!

>the duck always follows the nearest player.

I still haven't tested it in multiplayer so - are you saying there can only be one duck per lobby? :(
Aw, I was hoping it was a personal pet (1 per player), each following its owner.

>the duck always follows the nearest player.

Since you mentioned this - sorry to overcomplicate things but, is the duck properly replicated between players?

1) ==========
I can already see this scenario happening if there's a single duck(or more) and 2 people (or more):

- the duck will initially follow one player (let's call the followed player as "leader")
- the duck will initially follow the leader, who currently has no scrap and is headed to the dungeon
- at some point the duck will get confused as soon as it meets another "nearest" player, regardless of the "state" the player is in (headed to the factory/headed to the ship), and regardless of the duck carrying loot or not.
- Issue: the duck will follow a random player regardless of the fact the new leader is headed or not inside the dungeon or if the duck is carrying an item or not. This could lead to a scenario where the duck never ever returns to the ship until all players return to the ship - severely limiting its utility.

Potential fixes (unless you're okay with the duck getting "confused"):
- fix A) the most complicated but most predictable: the duck is idle when it arrives. it gets loyal to the player that interacts with it up until 1) the player dies 2) the player disconnects. A duck with no owner returns to the ship or becomes "idle"; when "Idle" it can be "tamed" by another player. This would allow for one or more ducks per player. (you could still make it a config to limit the number of ducks per player to a set number). Additionally, an "idle" duck could drop its loot if there's a player's body around, picks it, and gets back to "idle" ready to be "tamed" by another player.
- fix B) if the duck has no loot, it follows the nearest player and is "loyal" to him until the duck finds some loot. As soon as it finds some loot, the duck will follow the nearest visible player who's carrying the heaviest loot and sticks to the newest leader until the duck returns to the ship. If the leader dies, it waits for a couple of seconds (to handle death animations, the player getting eaten, etc.). After waiting, if the leader's corpse (or any player's corpse) is available: the duck drops any loot, and picks up the player's ragdoll. It can then (you choose) return to the ship to recover the body, or choose a new leader.
- fix C) probably the easiest: whoever last interacted ("used") with the duck becomes the duck's leader, until another player interacts with it. This would delegate to the players most of the logic, but the duck may feel a bit less "smart", potentially leading to players fighting to get the control over a duck (spamming the "interact" button on the duck).

Just a few ideas. I know it complicates things - please ignore me if it makes the development of the duck "too much", I'd rather have a less smart working duck, that no duck at all ;)

**Comment by Dio93** [comment]
Unfortunately, there can be only one duck per lobby. I've encountered sync issues when there is more than one duck and I don't know how to fix them.

Thanks for your suggestions, I really appreciate it.

The duck should be properly replicated between players. At the moment the ai isn't that smart. Each iteration it looks for the closest player and follows it. In the worst case the duck arrives at the ship when every player is returned. 

Since the in- and outdoors maps are distanced from each other, the duck will automatically follow the nearest player in the respective area it's currently in, meaning the duck won't follow a player inside the building if there's at least one other player outside as that player will always be closer to the duck than any players inside the building.

I'm planning a followup mod with more animals. Each animal may have different behavior and I'll take your ideas into account. 
But I don't know when I'll start this mod.

**Comment by NeatWolf** [comment]
Aw, I was considering creating something similar myself but since it would be my first LC mod, I guess I'm gonna start with something more basic. 

Bit sad hearing there can only be one T_T

Thanks for implementing the rubberbanding, it's -a lot- more useful now! 

Sometimes it gets stuck or doesn't follow you outside but I'll open a new issue when I have more data.

Keep up with the great job! :)
